#!/usr/bin/env bash
# a for loop to iterate through numbers from 1 to 100

for ((a=1; a<=100; a++));
do

# Check conditions for printing FizzBuzz

if ((a % 3 == 0)) && ((a % 5 == 0));
then
	echo "FizzBuzz"
elif ((a % 3 == 0));
then
	echo "Fizz"
elif ((a % 5 == 0));
then
	echo "Buzz"
else
	echo "$a"
fi
done
