#!/usr/bin/env bash
# Initialize a counter

counter=1

# a while loop to display messages based on the iteration

while [ $counter -le 10 ];
do
	if [ $counter -eq 4 ];
then
	echo "bad luck"
	elif [ $counter -eq 8 ];
then
	echo "good luck"
else
	echo "Best School"
fi
	((counter++))
done
