#!/usr/bin/env bash
# Initialize a counter

counter=1

# a while loop to display numbers and messages based on specific iterations

while [ $counter -le 20 ];
do
	case $counter in
	4)
		echo "$counter"
		echo "bad luck from China"
		;;
	9)
		echo "$counter"
		echo "bad luck from Japan"
		;;
	17)
		echo "$counter"
		echo "bad luck from Italy"
		;;
	*)
		echo "$counter"
		;;
	esac
	((counter++))
done
